h5ad_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.h5ad"
nodes_pickle: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.nodes.pickle"
misi_data_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.misidata.h5"
puc_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.puc.h5"
nrounds: 8
nsamples: 200
nobs: 0
nvars: 0
mode: "misi"
save_nodes: False
save_node_pairs: True
