h5ad_file: "/localscratch/schockalingam6/tmp/pbmc20k.2500/adata.20k.2500.h5ad"
misi_data_file: "/localscratch/schockalingam6/tmp/pbmc20k.2500/adata.20k.2500.misidata.h5"
puc_file: "/localscratch/schockalingam6/tmp/pbmc20k.2500/adata.20k.2500.S10x6p.par_puc.h5"
pidc_file: "/localscratch/schockalingam6/tmp/pbmc20k.2500/adata.20k.2500.S10x6p.par_pidc.h5"
#
nrounds: 10
nsamples: 150
nobs: 0
nvars: 0
mode:
  - "samples_ranges"
  - "puc2pidc"
save_nodes: False
save_node_pairs: True
